files:
  include: 'src/style/**/*.s+(a|c)ss'
  ignore:
    - 'src/style/vendor/**/*.*'

rules:
  bem-depth: 0
  nesting-depth: 0
  no-transition-all: 0
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 0
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 0
